<?xml version = "1.0"?>
<!DOCTYPE Component [
<!ELEMENT Component (CICB*)>
<!ATTLIST Component
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Num_CICBs CDATA #REQUIRED>
<!ELEMENT CICB (Provide|Require|Block_Point|EMPTY)>
<!ATTLIST CICB
Id CDATA #REQUIRED
Name CDATA #REQUIRED>
<!ELEMENT Provide (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Require (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Call_invoke_IDs EMPTY>
<!ELEMENT Variable_access_IDs EMPTY>
<!ELEMENT Point_Block (Selective|Conditional|Cyclic|Data)*>
<!ATTLIST Provide
Num_points CDATA #REQUIRED
Braced CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Selective (Point_Block*|EMPTY)>
<!ATTLIST Selective
If_Blocks CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Conditional (Point_Block|EMPTY)>
<!ATTLIST Conditional
Code_Loc CDATA #REQUIRED>
<!ELEMENT Cyclic (Point_Block|EMPTY)>
<!ATTLIST Cyclic
Id CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Data (Call|Variable|EMPTY)*>
<!ATTLIST Data
Data_owner CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Call (Data|EMPTY)>
<!ATTLIST Call
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Collect CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Access CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
]>
<Component
Id="219"
Name="backend.optimizer.plan.setrefs.c"
Num_CICBs="30">
<CICB
Id="0"
Name="Master">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="0">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="0">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(30,1),(1884,1)">
</Point_Block>
</CICB>
<CICB
Id="1"
Name="set_plan_refs">
<Provide
Num_call_invokes="2"
Num_Variable_accesses="13">
<Call_invoke_IDs>
7988 
7989 
</Call_invoke_IDs>
<Variable_access_IDs>
42711
42712
42713
42714
42715
42716
42717
42718
42719
42720
42721
42722
42723
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="7"
Num_Variable_accesses="13">
<Call_invoke_IDs>
7983 
7984 
7985 
7986 
7987 
7988 
7989 
</Call_invoke_IDs>
<Variable_access_IDs>
42711
42712
42713
42714
42715
42716
42717
42718
42719
42720
42721
42722
42723
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(247,2),(519,13)">
<Conditional
Code_Loc="(249,2),(250,14)">
</Conditional>
<Selective
If_Blocks="No"
Code_Loc="(255,2),(506,2)">
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(258,4),(267,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(269,4),(282,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(284,4),(296,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(298,4),(309,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(311,4),(322,9)">
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(325,4),(327,24)">
<Data
Data_owner="Jump"
Code_Loc="(325,4),(327,24)">
<Call
Id="7983"
Name="set_subqueryscan_references"
Collect="Absorbed"
Access_block="(219,1)"
Home_block="(219,2)">
<Data
Data_owner="CallParamaters"
Code_Loc="(325,4),(327,24)">
<Variable
Id="42711"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(329,4),(340,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(342,4),(353,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(355,4),(364,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(366,4),(375,9)">
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(379,4),(380,9)">
<Data
Data_owner="Expression"
Code_Loc="(379,4),(379,54)">
<Call
Id="7984"
Name="set_join_references"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,9)">
<Data
Data_owner="CallParamaters"
Code_Loc="(379,4),(379,54)">
<Variable
Id="42712"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(395,4),(402,9)">
<Data
Data_owner="Expression"
Code_Loc="(395,4),(395,46)">
<Call
Id="7985"
Name="set_dummy_tlist_references"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,12)">
<Data
Data_owner="CallParamaters"
Code_Loc="(395,4),(395,46)">
<Variable
Id="42713"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(401,4),(401,29)">
<Variable
Id="42714"
Name="plan"
Access="Write"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(404,4),(421,9)">
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(425,4),(426,9)">
<Data
Data_owner="Expression"
Code_Loc="(425,4),(425,46)">
<Call
Id="7986"
Name="set_upper_references"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,11)">
<Data
Data_owner="CallParamaters"
Code_Loc="(425,4),(425,46)">
<Variable
Id="42715"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(428,4),(448,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(450,4),(466,9)">
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(469,4),(471,9)">
<Data
Data_owner="Expression"
Code_Loc="(469,4),(469,46)">
<Call
Id="7987"
Name="set_dummy_tlist_references"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,12)">
<Data
Data_owner="CallParamaters"
Code_Loc="(469,4),(469,46)">
<Variable
Id="42716"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(470,4),(470,29)">
<Variable
Id="42717"
Name="plan"
Access="Write"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(473,4),(486,9)">
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(488,4),(501,9)">
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(503,4),(505,9)">
<Data
Data_owner="Expression"
Code_Loc="(503,4),(504,26)">
<Variable
Id="42718"
Name="plan"
Access="Write"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(516,2),(516,64)">
<Variable
Id="42719"
Name="plan"
Access="Write"
Access_block="(219,1)"
Home_block="(219,1)"/>
<Call
Id="7988"
Name="set_plan_refs"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,1)">
<Data
Data_owner="CallParamaters"
Code_Loc="(516,2),(516,64)">
<Variable
Id="42720"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(517,2),(517,66)">
<Variable
Id="42721"
Name="plan"
Access="Write"
Access_block="(219,1)"
Home_block="(219,1)"/>
<Call
Id="7989"
Name="set_plan_refs"
Collect="Bridged"
Access_block="(219,1)"
Home_block="(219,1)">
<Data
Data_owner="CallParamaters"
Code_Loc="(517,2),(517,66)">
<Variable
Id="42722"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(519,2),(519,13)">
<Variable
Id="42723"
Name="plan"
Access="Read"
Access_block="(219,1)"
Home_block="(219,1)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="2"
Name="set_subqueryscan_references">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="28">
<Call_invoke_IDs>
7983 
</Call_invoke_IDs>
<Variable_access_IDs>
42724
42725
42726
42727
42728
42729
42730
42731
42732
42733
42734
42735
42736
42737
42738
42739
42740
42741
42742
42743
42744
42745
42746
42747
42748
42749
42750
42751
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="28">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
42724
42725
42726
42727
42728
42729
42730
42731
42732
42733
42734
42735
42736
42737
42738
42739
42740
42741
42742
42743
42744
42745
42746
42747
42748
42749
42750
42751
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(534,2),(590,15)">
<Data
Data_owner="Expression"
Code_Loc="(537,2),(537,75)">
<Variable
Id="42724"
Name="plan"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42725"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42726"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(540,2),(540,23)">
<Variable
Id="42727"
Name="plan"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(542,2),(588,2)">
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(547,3),(570,3)">
<Data
Data_owner="Expression"
Code_Loc="(550,3),(550,25)">
<Variable
Id="42728"
Name="result"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42729"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(553,3),(554,30)">
<Variable
Id="42730"
Name="result"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42731"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42732"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42733"
Name="result"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Cyclic
Id="2643"
Code_Loc="(562,3),(570,3)">
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(564,4),(569,39)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(564,4),(564,50)">
<Variable
Id="42734"
Name="ptle"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42735"
Name="lp"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(565,4),(565,50)">
<Variable
Id="42736"
Name="ctle"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42737"
Name="lc"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(567,4),(567,33)">
<Variable
Id="42738"
Name="ctle"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42739"
Name="ptle"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(568,4),(568,39)">
<Variable
Id="42740"
Name="ctle"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42741"
Name="ptle"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(569,4),(569,39)">
<Variable
Id="42742"
Name="ctle"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42743"
Name="ptle"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
</Point_Block>
</Cyclic>
</Point_Block>
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(581,3),(587,25)">
<Data
Data_owner="Expression"
Code_Loc="(581,3),(581,35)">
<Variable
Id="42744"
Name="plan"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(582,3),(583,61)">
<Variable
Id="42745"
Name="plan"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42746"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(584,3),(585,55)">
<Variable
Id="42747"
Name="plan"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42748"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(587,3),(587,25)">
<Variable
Id="42749"
Name="result"
Access="Write"
Access_block="(219,2)"
Home_block="(219,2)"/>
<Variable
Id="42750"
Name="plan"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
</Point_Block>
</Selective>
<Data
Data_owner="Jump"
Code_Loc="(590,2),(590,15)">
<Variable
Id="42751"
Name="result"
Access="Read"
Access_block="(219,2)"
Home_block="(219,2)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="3"
Name="trivial_subqueryscan">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="10">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
42752
42753
42754
42755
42756
42757
42758
42759
42760
42761
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="10">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
42752
42753
42754
42755
42756
42757
42758
42759
42760
42761
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(603,2),(648,13)">
<Conditional
Code_Loc="(607,2),(608,15)">
</Conditional>
<Conditional
Code_Loc="(610,2),(612,15)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(614,2),(614,12)">
<Variable
Id="42752"
Name="attrno"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Cyclic
Id="2644"
Code_Loc="(615,2),(646,2)">
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(617,3),(645,11)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(617,3),(617,49)">
<Variable
Id="42753"
Name="ptle"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
<Variable
Id="42754"
Name="lp"
Access="Read"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(618,3),(618,49)">
<Variable
Id="42755"
Name="ctle"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
<Variable
Id="42756"
Name="lc"
Access="Read"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Conditional
Code_Loc="(620,3),(621,16)">
</Conditional>
<Selective
If_Blocks="Yes"
Code_Loc="(628,3),(643,16)">
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(630,4),(635,17)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(630,4),(630,37)">
<Variable
Id="42757"
Name="var"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
<Variable
Id="42758"
Name="ptle"
Access="Read"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(632,4),(632,46)">
<Variable
Id="42759"
Name="var"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(633,4),(633,33)">
<Variable
Id="42760"
Name="var"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
<Conditional
Code_Loc="(634,4),(635,17)">
</Conditional>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(645,3),(645,11)">
<Variable
Id="42761"
Name="attrno"
Access="Write"
Access_block="(219,3)"
Home_block="(219,3)"/>
</Data>
</Point_Block>
</Cyclic>
</Point_Block>
</CICB>
<CICB
Id="4"
Name="copyVar">
<Provide
Num_call_invokes="3"
Num_Variable_accesses="4">
<Call_invoke_IDs>
7990 
7991 
7992 
</Call_invoke_IDs>
<Variable_access_IDs>
42762
42763
42764
42765
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="4">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
42762
42763
42764
42765
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(661,2),(664,15)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(661,2),(661,47)">
<Variable
Id="42762"
Name="newvar"
Access="Write"
Access_block="(219,4)"
Home_block="(219,4)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(663,2),(663,16)">
<Variable
Id="42763"
Name="newvar"
Access="Write"
Access_block="(219,4)"
Home_block="(219,4)"/>
<Variable
Id="42764"
Name="var"
Access="Read"
Access_block="(219,4)"
Home_block="(219,4)"/>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(664,2),(664,15)">
<Variable
Id="42765"
Name="newvar"
Access="Read"
Access_block="(219,4)"
Home_block="(219,4)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="5"
Name="fix_expr_common">
<Provide
Num_call_invokes="5"
Num_Variable_accesses="0">
<Call_invoke_IDs>
7993 
7994 
7995 
7996 
7997 
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="0">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(683,2),(737,2)">
<Selective
If_Blocks="Yes"
Code_Loc="(683,2),(737,2)">
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(685,3),(686,39)">
</Point_Block>
</Selective>
</Point_Block>
</CICB>
<CICB
Id="6"
Name="fix_scan_expr">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="5">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
42766
42767
42768
42769
42770
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="2"
Num_Variable_accesses="5">
<Call_invoke_IDs>
7998 
7999 
</Call_invoke_IDs>
<Variable_access_IDs>
42766
42767
42768
42769
42770
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(751,2),(772,2)">
<Data
Data_owner="Expression"
Code_Loc="(753,2),(753,21)">
<Variable
Id="42766"
Name="context"
Access="Write"
Access_block="(219,6)"
Home_block="(219,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(754,2),(754,29)">
<Variable
Id="42767"
Name="context"
Access="Write"
Access_block="(219,6)"
Home_block="(219,6)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(756,2),(772,2)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(758,3),(758,47)">
<Data
Data_owner="Jump"
Code_Loc="(758,3),(758,47)">
<Call
Id="7998"
Name="fix_scan_expr_mutator"
Collect="Emanated"
Access_block="(219,6)"
Home_block="(219,7)">
<Data
Data_owner="CallParamaters"
Code_Loc="(758,3),(758,47)">
<Variable
Id="42768"
Name="node"
Access="Read"
Access_block="(219,6)"
Home_block="(219,6)"/>
</Data>
</Call>
</Data>
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(770,3),(771,14)">
<Data
Data_owner="Expression"
Code_Loc="(770,3),(770,46)">
<Call
Id="7999"
Name="fix_scan_expr_walker"
Collect="Emanated"
Access_block="(219,6)"
Home_block="(219,8)">
<Data
Data_owner="CallParamaters"
Code_Loc="(770,3),(770,46)">
<Variable
Id="42769"
Name="node"
Access="Read"
Access_block="(219,6)"
Home_block="(219,6)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(771,3),(771,14)">
<Variable
Id="42770"
Name="node"
Access="Read"
Access_block="(219,6)"
Home_block="(219,6)"/>
</Data>
</Point_Block>
</Selective>
</Point_Block>
</CICB>
<CICB
Id="7"
Name="fix_scan_expr_mutator">
<Provide
Num_call_invokes="3"
Num_Variable_accesses="8">
<Call_invoke_IDs>
7998 
8000 
8001 
</Call_invoke_IDs>
<Variable_access_IDs>
42771
42772
42773
42774
42775
42776
42777
42778
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="5"
Num_Variable_accesses="8">
<Call_invoke_IDs>
7990 
8000 
7993 
7463 
8001 
</Call_invoke_IDs>
<Variable_access_IDs>
42771
42772
42773
42774
42775
42776
42777
42778
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(778,2),(815,29)">
<Conditional
Code_Loc="(778,2),(779,14)">
</Conditional>
<Conditional
Code_Loc="(780,2),(796,2)">
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(782,3),(795,22)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(782,3),(782,39)">
<Variable
Id="42771"
Name="var"
Access="Write"
Access_block="(219,7)"
Home_block="(219,7)"/>
<Call
Id="7990"
Name="copyVar"
Collect="Absorbed"
Access_block="(219,7)"
Home_block="(219,4)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(784,3),(784,32)">
<Variable
Id="42772"
Name="var"
Access="Write"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(790,3),(790,30)">
<Variable
Id="42773"
Name="var"
Access="Write"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
<Conditional
Code_Loc="(791,3),(792,35)">
</Conditional>
<Conditional
Code_Loc="(793,3),(794,38)">
</Conditional>
<Data
Data_owner="Jump"
Code_Loc="(795,3),(795,22)">
<Variable
Id="42774"
Name="var"
Access="Read"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
</Point_Block>
</Conditional>
<Conditional
Code_Loc="(797,2),(805,2)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(799,3),(804,24)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(799,3),(799,60)">
<Variable
Id="42775"
Name="node"
Access="Write"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
</Point_Block>
</Conditional>
<Conditional
Code_Loc="(806,2),(812,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(809,3),(811,62)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(809,3),(809,48)">
<Variable
Id="42776"
Name="node"
Access="Write"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(811,3),(811,62)">
<Call
Id="8000"
Name="fix_scan_expr_mutator"
Collect="Bridged"
Access_block="(219,7)"
Home_block="(219,7)">
</Call>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(813,2),(813,38)">
<Call
Id="7993"
Name="fix_expr_common"
Collect="Absorbed"
Access_block="(219,7)"
Home_block="(219,5)">
<Data
Data_owner="CallParamaters"
Code_Loc="(813,2),(813,38)">
<Variable
Id="42777"
Name="context"
Access="Read"
Access_block="(219,7)"
Home_block="(219,7)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(814,2),(815,29)">
<Call
Id="7463"
Name="expression_tree_mutator"
Collect="Absorbed"
Access_block="(219,7)"
Home_block="(182,8)">
<Data
Data_owner="CallParamaters"
Code_Loc="(814,2),(815,29)">
<Variable
Id="42778"
Name="node"
Access="Read"
Access_block="(219,7)"
Home_block="(219,7)"/>
<Call
Id="8001"
Name="fix_scan_expr_mutator"
Collect="Bridged"
Access_block="(219,7)"
Home_block="(219,7)">
</Call>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="8"
Name="fix_scan_expr_walker">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="2">
<Call_invoke_IDs>
7999 
</Call_invoke_IDs>
<Variable_access_IDs>
42779
42780
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="2">
<Call_invoke_IDs>
7994 
</Call_invoke_IDs>
<Variable_access_IDs>
42779
42780
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(821,2),(826,28)">
<Conditional
Code_Loc="(821,2),(822,15)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(823,2),(823,36)">
<Variable
Id="42779"
Name="node"
Access="Write"
Access_block="(219,8)"
Home_block="(219,8)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(824,2),(824,38)">
<Call
Id="7994"
Name="fix_expr_common"
Collect="Absorbed"
Access_block="(219,8)"
Home_block="(219,5)">
<Data
Data_owner="CallParamaters"
Code_Loc="(824,2),(824,38)">
<Variable
Id="42780"
Name="context"
Access="Read"
Access_block="(219,8)"
Home_block="(219,8)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="9"
Name="set_join_references">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="13">
<Call_invoke_IDs>
7984 
</Call_invoke_IDs>
<Variable_access_IDs>
42781
42782
42783
42784
42785
42786
42787
42788
42789
42790
42791
42792
42793
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="6"
Num_Variable_accesses="13">
<Call_invoke_IDs>
8002 
8003 
8004 
8005 
8006 
8007 
</Call_invoke_IDs>
<Variable_access_IDs>
42781
42782
42783
42784
42785
42786
42787
42788
42789
42790
42791
42792
42793
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="8"
Braced="Yes"
Code_Loc="(844,2),(902,21)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(844,2),(844,43)">
<Variable
Id="42781"
Name="outer_plan"
Access="Write"
Access_block="(219,9)"
Home_block="(219,9)"/>
<Variable
Id="42782"
Name="join"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(845,2),(845,44)">
<Variable
Id="42783"
Name="inner_plan"
Access="Write"
Access_block="(219,9)"
Home_block="(219,9)"/>
<Variable
Id="42784"
Name="join"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(849,2),(849,58)">
<Call
Id="8002"
Name="build_tlist_index"
Collect="Absorbed"
Access_block="(219,9)"
Home_block="(219,13)">
<Data
Data_owner="CallParamaters"
Code_Loc="(849,2),(849,58)">
<Variable
Id="42785"
Name="outer_plan"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(850,2),(850,58)">
<Call
Id="8003"
Name="build_tlist_index"
Collect="Absorbed"
Access_block="(219,9)"
Home_block="(219,13)">
<Data
Data_owner="CallParamaters"
Code_Loc="(850,2),(850,58)">
<Variable
Id="42786"
Name="inner_plan"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(853,2),(858,22)">
<Variable
Id="42787"
Name="join"
Access="Write"
Access_block="(219,9)"
Home_block="(219,9)"/>
<Call
Id="8004"
Name="fix_join_expr"
Collect="Bridged"
Access_block="(219,9)"
Home_block="(219,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(853,2),(858,22)">
<Variable
Id="42788"
Name="join"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(859,2),(864,19)">
<Variable
Id="42789"
Name="join"
Access="Write"
Access_block="(219,9)"
Home_block="(219,9)"/>
<Call
Id="8005"
Name="fix_join_expr"
Collect="Bridged"
Access_block="(219,9)"
Home_block="(219,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(859,2),(864,19)">
<Variable
Id="42790"
Name="join"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(865,2),(870,21)">
<Variable
Id="42791"
Name="join"
Access="Write"
Access_block="(219,9)"
Home_block="(219,9)"/>
<Call
Id="8006"
Name="fix_join_expr"
Collect="Bridged"
Access_block="(219,9)"
Home_block="(219,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(865,2),(870,21)">
<Variable
Id="42792"
Name="join"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(873,2),(899,2)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(876,3),(876,60)">
<Data
Data_owner="Expression"
Code_Loc="(876,3),(876,60)">
<Call
Id="8007"
Name="set_inner_join_references"
Collect="Bridged"
Access_block="(219,9)"
Home_block="(219,10)">
<Data
Data_owner="CallParamaters"
Code_Loc="(876,3),(876,60)">
<Variable
Id="42793"
Name="inner_plan"
Access="Read"
Access_block="(219,9)"
Home_block="(219,9)"/>
</Data>
</Call>
</Data>
</Point_Block>
</Selective>
</Point_Block>
</CICB>
<CICB
Id="10"
Name="set_inner_join_references">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="10">
<Call_invoke_IDs>
8007 
</Call_invoke_IDs>
<Variable_access_IDs>
42794
42795
42796
42797
42798
42799
42800
42801
42802
42803
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="2"
Num_Variable_accesses="10">
<Call_invoke_IDs>
8008 
8009 
</Call_invoke_IDs>
<Variable_access_IDs>
42794
42795
42796
42797
42798
42799
42800
42801
42802
42803
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(922,2),(1089,2)">
<Selective
If_Blocks="Yes"
Code_Loc="(922,2),(1089,2)">
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(930,3),(964,3)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(930,3),(930,51)">
<Variable
Id="42794"
Name="innerscan"
Access="Write"
Access_block="(219,10)"
Home_block="(219,10)"/>
<Variable
Id="42795"
Name="inner_plan"
Access="Read"
Access_block="(219,10)"
Home_block="(219,10)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(931,3),(931,52)">
<Variable
Id="42796"
Name="innerscan"
Access="Write"
Access_block="(219,10)"
Home_block="(219,10)"/>
</Data>
<Conditional
Code_Loc="(934,3),(964,3)">
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(936,4),(963,16)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(936,4),(936,47)">
<Variable
Id="42797"
Name="innerrel"
Access="Write"
Access_block="(219,10)"
Home_block="(219,10)"/>
<Variable
Id="42798"
Name="innerscan"
Access="Read"
Access_block="(219,10)"
Home_block="(219,10)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(939,4),(944,17)">
<Variable
Id="42799"
Name="innerscan"
Access="Write"
Access_block="(219,10)"
Home_block="(219,10)"/>
<Call
Id="8008"
Name="fix_join_expr"
Collect="Bridged"
Access_block="(219,10)"
Home_block="(219,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(939,4),(944,17)">
<Variable
Id="42800"
Name="innerrel"
Access="Read"
Access_block="(219,10)"
Home_block="(219,10)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(945,4),(950,16)">
<Variable
Id="42801"
Name="innerscan"
Access="Write"
Access_block="(219,10)"
Home_block="(219,10)"/>
<Call
Id="8009"
Name="fix_join_expr"
Collect="Bridged"
Access_block="(219,10)"
Home_block="(219,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(945,4),(950,16)">
<Variable
Id="42802"
Name="innerscan"
Access="Read"
Access_block="(219,10)"
Home_block="(219,10)"/>
<Variable
Id="42803"
Name="innerrel"
Access="Read"
Access_block="(219,10)"
Home_block="(219,10)"/>
</Data>
</Call>
</Data>
<Conditional
Code_Loc="(957,4),(963,16)">
</Conditional>
</Point_Block>
</Conditional>
</Point_Block>
</Selective>
</Point_Block>
</CICB>
<CICB
Id="11"
Name="set_upper_references">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="13">
<Call_invoke_IDs>
7986 
</Call_invoke_IDs>
<Variable_access_IDs>
42804
42805
42806
42807
42808
42809
42810
42811
42812
42813
42814
42815
42816
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="4"
Num_Variable_accesses="13">
<Call_invoke_IDs>
8010 
8011 
7258 
8012 
</Call_invoke_IDs>
<Variable_access_IDs>
42804
42805
42806
42807
42808
42809
42810
42811
42812
42813
42814
42815
42816
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(1113,2),(1157,23)">
<Data
Data_owner="Expression"
Code_Loc="(1118,2),(1118,57)">
<Call
Id="8010"
Name="build_tlist_index"
Collect="Absorbed"
Access_block="(219,11)"
Home_block="(219,13)">
</Call>
</Data>
<Data