<?xml version = "1.0"?>
<!DOCTYPE Component [
<!ELEMENT Component (CICB*)>
<!ATTLIST Component
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Num_CICBs CDATA #REQUIRED>
<!ELEMENT CICB (Provide|Require|Block_Point|EMPTY)>
<!ATTLIST CICB
Id CDATA #REQUIRED
Name CDATA #REQUIRED>
<!ELEMENT Provide (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Require (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Call_invoke_IDs EMPTY>
<!ELEMENT Variable_access_IDs EMPTY>
<!ELEMENT Point_Block (Selective|Conditional|Cyclic|Data)*>
<!ATTLIST Provide
Num_points CDATA #REQUIRED
Braced CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Selective (Point_Block*|EMPTY)>
<!ATTLIST Selective
If_Blocks CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Conditional (Point_Block|EMPTY)>
<!ATTLIST Conditional
Code_Loc CDATA #REQUIRED>
<!ELEMENT Cyclic (Point_Block|EMPTY)>
<!ATTLIST Cyclic
Id CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Data (Call|Variable|EMPTY)*>
<!ATTLIST Data
Data_owner CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Call (Data|EMPTY)>
<!ATTLIST Call
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Collect CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Access CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
]>
<Component
Id="351"
Name="backend.storage.large_object.inv_api.c"
Num_CICBs="15">
<CICB
Id="0"
Name="Master">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="19">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64881
64882
64883
64884
64885
64886
64887
64888
64889
64890
64891
64892
64893
64894
64895
64896
64897
64898
64899
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64881
64882
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(57,1),(870,1)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(57,1),(57,33)">
<Variable
Id="64881"
Name="lo_heap_r"
Access="Write"
Access_block="(351,0)"
Home_block="(351,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(58,1),(58,34)">
<Variable
Id="64882"
Name="lo_index_r"
Access="Write"
Access_block="(351,0)"
Home_block="(351,0)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="1"
Name="open_lo_relation">
<Provide
Num_call_invokes="5"
Num_Variable_accesses="2">
<Call_invoke_IDs>
9719 
9720 
9721 
9722 
9723 
</Call_invoke_IDs>
<Variable_access_IDs>
64900
64903
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="4">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64900
64901
64902
64903
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(67,2),(91,37)">
<Conditional
Code_Loc="(69,2),(70,9)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(73,2),(73,37)">
<Variable
Id="64900"
Name="currentOwner"
Access="Write"
Access_block="(351,1)"
Home_block="(351,1)"/>
<Variable
Id="64901"
Name="CurrentResourceOwner"
Access="Read"
Access_block="(351,1)"
Home_block="(522,0)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(91,2),(91,37)">
<Variable
Id="64902"
Name="CurrentResourceOwner"
Access="Write"
Access_block="(351,1)"
Home_block="(522,0)"/>
<Variable
Id="64903"
Name="currentOwner"
Access="Read"
Access_block="(351,1)"
Home_block="(351,1)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="2"
Name="close_lo_relation">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64904
64907
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="6">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64904
64905
64906
64907
64883
64884
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(100,2),(131,2)">
<Conditional
Code_Loc="(100,2),(131,2)">
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(106,3),(130,20)">
<Conditional
Code_Loc="(106,3),(128,3)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(108,4),(127,39)">
<Data
Data_owner="Expression"
Code_Loc="(110,4),(110,39)">
<Variable
Id="64904"
Name="currentOwner"
Access="Write"
Access_block="(351,2)"
Home_block="(351,2)"/>
<Variable
Id="64905"
Name="CurrentResourceOwner"
Access="Read"
Access_block="(351,2)"
Home_block="(522,0)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(127,4),(127,39)">
<Variable
Id="64906"
Name="CurrentResourceOwner"
Access="Write"
Access_block="(351,2)"
Home_block="(522,0)"/>
<Variable
Id="64907"
Name="currentOwner"
Access="Read"
Access_block="(351,2)"
Home_block="(351,2)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(129,3),(129,19)">
<Variable
Id="64883"
Name="lo_heap_r"
Access="Write"
Access_block="(351,2)"
Home_block="(351,0)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(130,3),(130,20)">
<Variable
Id="64884"
Name="lo_index_r"
Access="Write"
Access_block="(351,2)"
Home_block="(351,0)"/>
</Data>
</Point_Block>
</Conditional>
</Point_Block>
</CICB>
<CICB
Id="3"
Name="myLargeObjectExists">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="6">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64908
64909
64910
64911
64912
64913
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="4"
Num_Variable_accesses="6">
<Call_invoke_IDs>
1228 
1874 
2000 
910 
</Call_invoke_IDs>
<Variable_access_IDs>
64908
64909
64910
64911
64912
64913
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="8"
Braced="Yes"
Code_Loc="(142,2),(167,15)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(142,2),(142,22)">
<Variable
Id="64908"
Name="retval"
Access="Write"
Access_block="(351,3)"
Home_block="(351,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(150,2),(153,28)">
<Variable
Id="64909"
Name="skey"
Access="Write"
Access_block="(351,3)"
Home_block="(351,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(155,2),(155,68)">
<Variable
Id="64910"
Name="pg_largeobject"
Access="Write"
Access_block="(351,3)"
Home_block="(351,3)"/>
<Call
Id="1228"
Name="heap_open"
Collect="Emanated"
Access_block="(351,3)"
Home_block="(36,10)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(157,2),(158,26)">
<Variable
Id="64911"
Name="sd"
Access="Write"
Access_block="(351,3)"
Home_block="(351,3)"/>
<Call
Id="1874"
Name="systable_beginscan"
Collect="Emanated"
Access_block="(351,3)"
Home_block="(43,3)">
<Data
Data_owner="CallParamaters"
Code_Loc="(157,2),(158,26)">
<Variable
Id="64912"
Name="pg_largeobject"
Access="Read"
Access_block="(351,3)"
Home_block="(351,3)"/>
</Data>
</Call>
</Data>
<Conditional
Code_Loc="(160,2),(161,16)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(163,2),(163,22)">
<Call
Id="2000"
Name="systable_endscan"
Collect="Emanated"
Access_block="(351,3)"
Home_block="(43,6)">
</Call>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(167,2),(167,15)">
<Variable
Id="64913"
Name="retval"
Access="Read"
Access_block="(351,3)"
Home_block="(351,3)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="4"
Name="getbytealen">
<Provide
Num_call_invokes="4"
Num_Variable_accesses="0">
<Call_invoke_IDs>
9724 
9725 
9726 
9727 
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="0">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(174,2),(177,35)">
<Conditional
Code_Loc="(175,2),(176,39)">
</Conditional>
</Point_Block>
</CICB>
<CICB
Id="5"
Name="inv_create">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64914
64915
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="3"
Num_Variable_accesses="2">
<Call_invoke_IDs>
9719 
3778 
2517 
</Call_invoke_IDs>
<Variable_access_IDs>
64914
64915
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(201,2),(220,15)">
<Conditional
Code_Loc="(201,2),(207,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(203,3),(206,35)">
<Data
Data_owner="Expression"
Code_Loc="(203,3),(203,21)">
<Call
Id="9719"
Name="open_lo_relation"
Collect="Emanated"
Access_block="(351,5)"
Home_block="(351,1)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(205,3),(206,35)">
<Variable
Id="64914"
Name="lobjId"
Access="Write"
Access_block="(351,5)"
Home_block="(351,5)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(213,2),(213,27)">
<Call
Id="3778"
Name="LargeObjectCreate"
Collect="Emanated"
Access_block="(351,5)"
Home_block="(81,1)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(218,2),(218,27)">
<Call
Id="2517"
Name="CommandCounterIncrement"
Collect="Emanated"
Access_block="(351,5)"
Home_block="(62,17)">
</Call>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(220,2),(220,15)">
<Variable
Id="64915"
Name="lobjId"
Access="Read"
Access_block="(351,5)"
Home_block="(351,5)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="6"
Name="inv_open">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="9">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64916
64917
64918
64919
64920
64921
64922
64923
64924
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="9">
<Call_invoke_IDs>
2412 
</Call_invoke_IDs>
<Variable_access_IDs>
64916
64917
64918
64919
64920
64921
64922
64923
64924
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="7"
Braced="Yes"
Code_Loc="(234,2),(268,15)">
<Data
Data_owner="Expression"
Code_Loc="(236,2),(237,38)">
<Variable
Id="64916"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
<Variable
Id="64917"
Name="mcxt"
Access="Read"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(239,2),(239,21)">
<Variable
Id="64918"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
<Variable
Id="64919"
Name="lobjId"
Access="Read"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(240,2),(240,46)">
<Variable
Id="64920"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
<Call
Id="2412"
Name="GetCurrentSubTransactionId"
Collect="Emanated"
Access_block="(351,6)"
Home_block="(62,8)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(241,2),(241,20)">
<Variable
Id="64921"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(243,2),(260,42)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(245,3),(246,42)">
<Data
Data_owner="Expression"
Code_Loc="(245,3),(245,33)">
<Variable
Id="64922"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(246,3),(246,42)">
<Variable
Id="64923"
Name="retval"
Access="Write"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
</Point_Block>
</Selective>
<Conditional
Code_Loc="(263,2),(266,56)">
</Conditional>
<Data
Data_owner="Jump"
Code_Loc="(268,2),(268,15)">
<Variable
Id="64924"
Name="retval"
Access="Read"
Access_block="(351,6)"
Home_block="(351,6)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="7"
Name="inv_close">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64925
64926
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64925
64926
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(278,2),(284,17)">
<Data
Data_owner="Expression"
Code_Loc="(278,2),(278,34)">
<Variable
Id="64925"
Name="obj_desc"
Access="Write"
Access_block="(351,7)"
Home_block="(351,7)"/>
</Data>
<Conditional
Code_Loc="(280,2),(282,38)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(284,2),(284,17)">
<Variable
Id="64926"
Name="obj_desc"
Access="Write"
Access_block="(351,7)"
Home_block="(351,7)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="8"
Name="inv_drop">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64927
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="3"
Num_Variable_accesses="1">
<Call_invoke_IDs>
3779 
4044 
2518 
</Call_invoke_IDs>
<Variable_access_IDs>
64927
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(295,2),(306,10)">
<Data
Data_owner="Expression"
Code_Loc="(295,2),(295,25)">
<Call
Id="3779"
Name="LargeObjectDrop"
Collect="Emanated"
Access_block="(351,8)"
Home_block="(81,2)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(298,2),(298,50)">
<Call
Id="4044"
Name="DeleteComments"
Collect="Emanated"
Access_block="(351,8)"
Home_block="(94,4)">
<Data
Data_owner="CallParamaters"
Code_Loc="(298,2),(298,50)">
<Variable
Id="64927"
Name="lobjId"
Access="Read"
Access_block="(351,8)"
Home_block="(351,8)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(304,2),(304,27)">
<Call
Id="2518"
Name="CommandCounterIncrement"
Collect="Emanated"
Access_block="(351,8)"
Home_block="(62,17)">
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="9"
Name="inv_getsize">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="19">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64928
64929
64930
64931
64932
64933
64934
64935
64936
64937
64938
64939
64940
64941
64942
64943
64944
64945
64946
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="4"
Num_Variable_accesses="21">
<Call_invoke_IDs>
9720 
2017 
9724 
2022 
</Call_invoke_IDs>
<Variable_access_IDs>
64928
64929
64930
64931
64932
64885
64886
64933
64934
64935
64936
64937
64938
64939
64940
64941
64942
64943
64944
64945
64946
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="10"
Braced="Yes"
Code_Loc="(318,2),(372,17)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(318,2),(318,21)">
<Variable
Id="64928"
Name="found"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(319,2),(319,22)">
<Variable
Id="64929"
Name="lastbyte"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(324,2),(324,34)">
<Variable
Id="64930"
Name="obj_desc"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(326,2),(326,20)">
<Call
Id="9720"
Name="open_lo_relation"
Collect="Emanated"
Access_block="(351,9)"
Home_block="(351,1)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(328,2),(331,36)">
<Variable
Id="64931"
Name="skey"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(333,2),(334,38)">
<Variable
Id="64932"
Name="sd"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Call
Id="2017"
Name="systable_beginscan_ordered"
Collect="Emanated"
Access_block="(351,9)"
Home_block="(43,7)">
<Data
Data_owner="CallParamaters"
Code_Loc="(333,2),(334,38)">
<Variable
Id="64885"
Name="lo_heap_r"
Access="Read"
Access_block="(351,9)"
Home_block="(351,0)"/>
<Variable
Id="64886"
Name="lo_index_r"
Access="Read"
Access_block="(351,9)"
Home_block="(351,0)"/>
<Variable
Id="64933"
Name="obj_desc"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
</Call>
</Data>
<Cyclic
Id="3400"
Code_Loc="(342,2),(364,2)">
<Point_Block
Num_points="8"
Braced="Yes"
Code_Loc="(344,3),(363,8)">
<Data
Data_owner="Expression"
Code_Loc="(348,3),(348,15)">
<Variable
Id="64934"
Name="found"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Conditional
Code_Loc="(349,3),(350,53)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(351,3),(351,48)">
<Variable
Id="64935"
Name="data"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Variable
Id="64936"
Name="tuple"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(352,3),(352,28)">
<Variable
Id="64937"
Name="datafield"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Variable
Id="64938"
Name="data"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Variable
Id="64939"
Name="data"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(353,3),(353,18)">
<Variable
Id="64940"
Name="pfreeit"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Conditional
Code_Loc="(354,3),(359,3)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(356,4),(358,18)">
<Data
Data_owner="Expression"
Code_Loc="(356,4),(357,58)">
<Variable
Id="64941"
Name="datafield"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Variable
Id="64942"
Name="datafield"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(358,4),(358,18)">
<Variable
Id="64943"
Name="pfreeit"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(360,3),(360,63)">
<Variable
Id="64944"
Name="lastbyte"
Access="Write"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Variable
Id="64945"
Name="data"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
<Call
Id="9724"
Name="getbytealen"
Collect="Emanated"
Access_block="(351,9)"
Home_block="(351,4)">
</Call>
</Data>
<Conditional
Code_Loc="(361,3),(362,20)">
</Conditional>
</Point_Block>
</Cyclic>
<Data
Data_owner="Expression"
Code_Loc="(366,2),(366,30)">
<Call
Id="2022"
Name="systable_endscan_ordered"
Collect="Emanated"
Access_block="(351,9)"
Home_block="(43,9)">
</Call>
</Data>
<Conditional
Code_Loc="(368,2),(371,62)">
</Conditional>
<Data
Data_owner="Jump"
Code_Loc="(372,2),(372,17)">
<Variable
Id="64946"
Name="lastbyte"
Access="Read"
Access_block="(351,9)"
Home_block="(351,9)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="10"
Name="inv_seek">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="5">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64947
64948
64949
64950
64951
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="5">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64947
64948
64949
64950
64951
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(378,2),(404,25)">
<Data
Data_owner="Expression"
Code_Loc="(378,2),(378,34)">
<Variable
Id="64947"
Name="obj_desc"
Access="Write"
Access_block="(351,10)"
Home_block="(351,10)"/>
</Data>
<Selective
If_Blocks="No"
Code_Loc="(380,2),(403,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(383,4),(386,9)">
<Conditional
Code_Loc="(383,4),(384,51)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(385,4),(385,29)">
<Variable
Id="64948"
Name="obj_desc"
Access="Write"
Access_block="(351,10)"
Home_block="(351,10)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(388,4),(391,9)">
<Conditional
Code_Loc="(388,4),(389,51)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(390,4),(390,30)">
<Variable
Id="64949"
Name="obj_desc"
Access="Write"
Access_block="(351,10)"
Home_block="(351,10)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="0"
Braced="Yes"
Code_Loc="(393,4),(400,9)">
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(402,4),(402,45)">
<Data
Data_owner="Expression"
Code_Loc="(402,4),(402,45)">
<Variable
Id="64950"
Name="whence"
Access="Write"
Access_block="(351,10)"
Home_block="(351,10)"/>
</Data>
</Point_Block>
</Selective>
<Data
Data_owner="Jump"
Code_Loc="(404,2),(404,25)">
<Variable
Id="64951"
Name="obj_desc"
Access="Read"
Access_block="(351,10)"
Home_block="(351,10)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="11"
Name="inv_tell">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64952
64953
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64952
64953
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(410,2),(412,25)">
<Data
Data_owner="Expression"
Code_Loc="(410,2),(410,34)">
<Variable
Id="64952"
Name="obj_desc"
Access="Write"
Access_block="(351,11)"
Home_block="(351,11)"/>
</Data>
<Data
Data_owner="Jump"
Code_Loc="(412,2),(412,25)">
<Variable
Id="64953"
Name="obj_desc"
Access="Read"
Access_block="(351,11)"
Home_block="(351,11)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="12"
Name="inv_read">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="63">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
64954
64955
64956
64957
64958
64959
64960
64961
64962
64963
64964
64965
64966
64967
64968
64969
64970
64971
64972
64973
64974
64975
64976
64977
64978
64979
64980
64981
64982
64983
64984
64985
64986
64987
64988
64989
64990
64991
64992
64993
64994
64995
64996
64997
64998
64999
65000
65001
65002
65003
65004
65005
65006
65007
65008
65009
65010
65011
65012
65013
65014
65015
65016
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="4"
Num_Variable_accesses="65">
<Call_invoke_IDs>
9721 
2018 
9725 
2023 
</Call_invoke_IDs>
<Variable_access_IDs>
64954
64955
64956
64957
64958
64959
64960
64887
64888
64961
64962
64963
64964
64965
64966
64967
64968
64969
64970
64971
64972
64973
64974
64975
64976
64977
64978
64979
64980
64981
64982
64983
64984
64985
64986
64987
64988
64989
64990
64991
64992
64993
64994
64995
64996
64997
64998
64999
65000
65001
65002
65003
65004
65005
65006
65007
65008
65009
65010
65011
65012
65013
65014
65015
65016
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="12"
Braced="Yes"
Code_Loc="(418,2),(507,14)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(418,2),(418,17)">
<Variable
Id="64954"
Name="nread"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(422,2),(422,56)">
<Variable
Id="64955"
Name="obj_desc"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(428,2),(428,34)">
<Variable
Id="64956"
Name="obj_desc"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(429,2),(429,21)">
<Variable
Id="64957"
Name="buf"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Conditional
Code_Loc="(431,2),(432,11)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(434,2),(434,20)">
<Call
Id="9721"
Name="open_lo_relation"
Collect="Emanated"
Access_block="(351,12)"
Home_block="(351,1)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(436,2),(439,36)">
<Variable
Id="64958"
Name="skey"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(441,2),(444,27)">
<Variable
Id="64959"
Name="skey"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(446,2),(447,38)">
<Variable
Id="64960"
Name="sd"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Call
Id="2018"
Name="systable_beginscan_ordered"
Collect="Emanated"
Access_block="(351,12)"
Home_block="(43,7)">
<Data
Data_owner="CallParamaters"
Code_Loc="(446,2),(447,38)">
<Variable
Id="64887"
Name="lo_heap_r"
Access="Read"
Access_block="(351,12)"
Home_block="(351,0)"/>
<Variable
Id="64888"
Name="lo_index_r"
Access="Read"
Access_block="(351,12)"
Home_block="(351,0)"/>
<Variable
Id="64961"
Name="obj_desc"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
</Call>
</Data>
<Cyclic
Id="3401"
Code_Loc="(449,2),(503,2)">
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(451,3),(502,9)">
<Conditional
Code_Loc="(455,3),(456,53)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(457,3),(457,48)">
<Variable
Id="64962"
Name="data"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64963"
Name="tuple"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(464,3),(464,48)">
<Variable
Id="64964"
Name="pageoff"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64965"
Name="data"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Conditional
Code_Loc="(465,3),(472,3)">
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(467,4),(471,25)">
<Data
Data_owner="Expression"
Code_Loc="(467,4),(467,34)">
<Variable
Id="64966"
Name="n"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64967"
Name="pageoff"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64968"
Name="obj_desc"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(468,4),(468,54)">
<Variable
Id="64969"
Name="n"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64970"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64971"
Name="nbytes"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64972"
Name="nread"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64973"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64974"
Name="nbytes"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64975"
Name="nread"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(469,4),(469,29)">
<Variable
Id="64976"
Name="buf"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64977"
Name="nread"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64978"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(470,4),(470,14)">
<Variable
Id="64979"
Name="nread"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64980"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(471,4),(471,25)">
<Variable
Id="64981"
Name="obj_desc"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64982"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
</Point_Block>
</Conditional>
<Conditional
Code_Loc="(474,3),(499,3)">
<Point_Block
Num_points="9"
Braced="Yes"
Code_Loc="(476,4),(498,21)">
<Data
Data_owner="Expression"
Code_Loc="(476,4),(476,39)">
<Variable
Id="64983"
Name="obj_desc"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64984"
Name="pageoff"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(477,4),(477,44)">
<Variable
Id="64985"
Name="off"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64986"
Name="obj_desc"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64987"
Name="pageoff"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(478,4),(478,39)">
<Variable
Id="64988"
Name="off"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64989"
Name="off"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(480,4),(480,29)">
<Variable
Id="64990"
Name="datafield"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64991"
Name="data"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64992"
Name="data"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(481,4),(481,19)">
<Variable
Id="64993"
Name="pfreeit"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Conditional
Code_Loc="(482,4),(487,4)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(484,5),(486,19)">
<Data
Data_owner="Expression"
Code_Loc="(484,5),(485,59)">
<Variable
Id="64994"
Name="datafield"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64995"
Name="datafield"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(486,5),(486,19)">
<Variable
Id="64996"
Name="pfreeit"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(488,4),(488,32)">
<Variable
Id="64997"
Name="len"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Call
Id="9725"
Name="getbytealen"
Collect="Emanated"
Access_block="(351,12)"
Home_block="(351,4)">
</Call>
</Data>
<Conditional
Code_Loc="(489,4),(496,4)">
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(491,5),(495,26)">
<Data
Data_owner="Expression"
Code_Loc="(491,5),(491,18)">
<Variable
Id="64998"
Name="n"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="64999"
Name="len"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65000"
Name="off"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(492,5),(492,55)">
<Variable
Id="65001"
Name="n"
Access="Write"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65002"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65003"
Name="nbytes"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65004"
Name="nread"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65005"
Name="n"
Access="Read"
Access_block="(351,12)"
Home_block="(351,12)"/>
<Variable
Id="65006"
Name="nbytes"
Access="Read"