<?xml version = "1.0"?>
<!DOCTYPE Component [
<!ELEMENT Component (CICB*)>
<!ATTLIST Component
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Num_CICBs CDATA #REQUIRED>
<!ELEMENT CICB (Provide|Require|Block_Point|EMPTY)>
<!ATTLIST CICB
Id CDATA #REQUIRED
Name CDATA #REQUIRED>
<!ELEMENT Provide (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Require (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Call_invoke_IDs EMPTY>
<!ELEMENT Variable_access_IDs EMPTY>
<!ELEMENT Point_Block (Selective|Conditional|Cyclic|Data)*>
<!ATTLIST Provide
Num_points CDATA #REQUIRED
Braced CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Selective (Point_Block*|EMPTY)>
<!ATTLIST Selective
If_Blocks CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Conditional (Point_Block|EMPTY)>
<!ATTLIST Conditional
Code_Loc CDATA #REQUIRED>
<!ELEMENT Cyclic (Point_Block|EMPTY)>
<!ATTLIST Cyclic
Id CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Data (Call|Variable|EMPTY)*>
<!ATTLIST Data
Data_owner CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Call (Data|EMPTY)>
<!ATTLIST Call
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Collect CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Access CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
]>
<Component
Id="538"
Name="bin.pg_dump.pg_backup_custom.c"
Num_CICBs="31">
<CICB
Id="0"
Name="Master">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102324
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102324
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(34,1),(1104,1)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(97,1),(97,64)">
<Variable
Id="102324"
Name="modulename"
Access="Write"
Access_block="(538,0)"
Home_block="(538,0)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="1"
Name="InitArchiveFmt_Custom">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="42">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102325
102326
102327
102328
102329
102330
102331
102332
102333
102334
102335
102336
102337
102338
102339
102340
102341
102342
102343
102344
102345
102346
102347
102348
102349
102350
102351
102352
102353
102354
102355
102356
102357
102358
102359
102360
102361
102362
102363
102364
102365
102366
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="25"
Num_Variable_accesses="42">
<Call_invoke_IDs>
13786 
13787 
13788 
13789 
13790 
13791 
13792 
13793 
13794 
13795 
13796 
13797 
13798 
13799 
13800 
13801 
13802 
13803 
13804 
13805 
13768 
13769 
13765 
13748 
13806 
</Call_invoke_IDs>
<Variable_access_IDs>
102325
102326
102327
102328
102329
102330
102331
102332
102333
102334
102335
102336
102337
102338
102339
102340
102341
102342
102343
102344
102345
102346
102347
102348
102349
102350
102351
102352
102353
102354
102355
102356
102357
102358
102359
102360
102361
102362
102363
102364
102365
102366
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="34"
Braced="Yes"
Code_Loc="(114,2),(216,2)">
<Data
Data_owner="Expression"
Code_Loc="(117,2),(117,37)">
<Variable
Id="102325"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13786"
Name="_ArchiveEntry"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,2)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(118,2),(118,31)">
<Variable
Id="102326"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13787"
Name="_StartData"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,6)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(119,2),(119,31)">
<Variable
Id="102327"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13788"
Name="_WriteData"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,7)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(120,2),(120,27)">
<Variable
Id="102328"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13789"
Name="_EndData"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,8)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(121,2),(121,31)">
<Variable
Id="102329"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13790"
Name="_WriteByte"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,18)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(122,2),(122,29)">
<Variable
Id="102330"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13791"
Name="_ReadByte"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,19)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(123,2),(123,29)">
<Variable
Id="102331"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13792"
Name="_WriteBuf"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,20)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(124,2),(124,27)">
<Variable
Id="102332"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13793"
Name="_ReadBuf"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,21)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(125,2),(125,30)">
<Variable
Id="102333"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13794"
Name="_CloseArchive"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,22)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(126,2),(126,32)">
<Variable
Id="102334"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13795"
Name="_ReopenArchive"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,23)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(127,2),(127,37)">
<Variable
Id="102335"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13796"
Name="_PrintTocData"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,13)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(128,2),(128,37)">
<Variable
Id="102336"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13797"
Name="_ReadExtraToc"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,4)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(129,2),(129,39)">
<Variable
Id="102337"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13798"
Name="_WriteExtraToc"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,3)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(130,2),(130,39)">
<Variable
Id="102338"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13799"
Name="_PrintExtraToc"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,5)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(132,2),(132,33)">
<Variable
Id="102339"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13800"
Name="_StartBlobs"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,9)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(133,2),(133,31)">
<Variable
Id="102340"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13801"
Name="_StartBlob"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,10)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(134,2),(134,27)">
<Variable
Id="102341"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13802"
Name="_EndBlob"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,11)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(135,2),(135,29)">
<Variable
Id="102342"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13803"
Name="_EndBlobs"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(538,12)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(136,2),(136,23)">
<Variable
Id="102343"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13804"
Name="_Clone"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,29)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(137,2),(137,27)">
<Variable
Id="102344"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13805"
Name="_DeClone"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,30)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(142,2),(142,52)">
<Variable
Id="102345"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(143,2),(144,50)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(145,2),(145,31)">
<Variable
Id="102346"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Variable
Id="102347"
Name="ctx"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(147,2),(147,48)">
<Variable
Id="102348"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(148,2),(149,50)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(152,2),(152,30)">
<Variable
Id="102349"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(153,2),(153,42)">
<Variable
Id="102350"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(154,2),(155,50)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(164,2),(164,49)">
<Variable
Id="102351"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(165,2),(165,43)">
<Variable
Id="102352"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(166,2),(166,26)">
<Variable
Id="102353"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(167,2),(167,18)">
<Variable
Id="102354"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(169,2),(170,50)">
</Conditional>
<Selective
If_Blocks="Yes"
Code_Loc="(175,2),(216,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(177,3),(192,35)">
<Selective
If_Blocks="Yes"
Code_Loc="(177,3),(190,3)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(179,4),(182,36)">
<Data
Data_owner="Expression"
Code_Loc="(179,4),(179,42)">
<Variable
Id="102355"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Variable
Id="102356"
Name="AH"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(180,4),(182,36)">
</Conditional>
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(186,4),(189,25)">
<Data
Data_owner="Expression"
Code_Loc="(186,4),(186,19)">
<Variable
Id="102357"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(187,4),(189,25)">
</Conditional>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(192,3),(192,35)">
<Variable
Id="102358"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13768"
Name="checkSeek"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(537,58)">
<Data
Data_owner="CallParamaters"
Code_Loc="(192,3),(192,35)">
<Variable
Id="102359"
Name="AH"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
</Call>
</Data>
</Point_Block>
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(196,3),(215,40)">
<Selective
If_Blocks="Yes"
Code_Loc="(196,3),(209,3)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(198,4),(201,36)">
<Data
Data_owner="Expression"
Code_Loc="(198,4),(198,42)">
<Variable
Id="102360"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Variable
Id="102361"
Name="AH"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(199,4),(201,36)">
</Conditional>
</Point_Block>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(205,4),(208,25)">
<Data
Data_owner="Expression"
Code_Loc="(205,4),(205,18)">
<Variable
Id="102362"
Name="AH"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
<Conditional
Code_Loc="(206,4),(208,25)">
</Conditional>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(211,3),(211,35)">
<Variable
Id="102363"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13769"
Name="checkSeek"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(537,58)">
<Data
Data_owner="CallParamaters"
Code_Loc="(211,3),(211,35)">
<Variable
Id="102364"
Name="AH"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(213,3),(213,15)">
<Call
Id="13765"
Name="ReadHead"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(537,57)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(214,3),(214,14)">
<Call
Id="13748"
Name="ReadToc"
Collect="Emanated"
Access_block="(538,1)"
Home_block="(537,41)">
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(215,3),(215,40)">
<Variable
Id="102365"
Name="ctx"
Access="Write"
Access_block="(538,1)"
Home_block="(538,1)"/>
<Call
Id="13806"
Name="_getFilePos"
Collect="Absorbed"
Access_block="(538,1)"
Home_block="(538,24)">
<Data
Data_owner="CallParamaters"
Code_Loc="(215,3),(215,40)">
<Variable
Id="102366"
Name="AH"
Access="Read"
Access_block="(538,1)"
Home_block="(538,1)"/>
</Data>
</Call>
</Data>
</Point_Block>
</Selective>
</Point_Block>
</CICB>
<CICB
Id="2"
Name="_ArchiveEntry">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="2">
<Call_invoke_IDs>
13786 
</Call_invoke_IDs>
<Variable_access_IDs>
102367
102368
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="2">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102367
102368
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(230,2),(238,31)">
<Data
Data_owner="Expression"
Code_Loc="(232,2),(232,54)">
<Variable
Id="102367"
Name="ctx"
Access="Write"
Access_block="(538,2)"
Home_block="(538,2)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(233,2),(236,36)">
</Selective>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(238,2),(238,31)">
<Variable
Id="102368"
Name="ctx"
Access="Write"
Access_block="(538,2)"
Home_block="(538,2)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="3"
Name="_WriteExtraToc">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13798 
</Call_invoke_IDs>
<Variable_access_IDs>
102369
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102369
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(253,2),(255,47)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(253,2),(253,51)">
<Variable
Id="102369"
Name="ctx"
Access="Write"
Access_block="(538,3)"
Home_block="(538,3)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="4"
Name="_ReadExtraToc">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="4">
<Call_invoke_IDs>
13797 
</Call_invoke_IDs>
<Variable_access_IDs>
102370
102371
102372
102373
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="4">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102370
102371
102372
102373
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="4"
Braced="Yes"
Code_Loc="(269,2),(285,21)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(270,2),(270,51)">
<Variable
Id="102370"
Name="ctx"
Access="Write"
Access_block="(538,4)"
Home_block="(538,4)"/>
</Data>
<Conditional
Code_Loc="(272,2),(276,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(274,3),(275,32)">
<Data
Data_owner="Expression"
Code_Loc="(274,3),(274,55)">
<Variable
Id="102371"
Name="ctx"
Access="Write"
Access_block="(538,4)"
Home_block="(538,4)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(275,3),(275,32)">
<Variable
Id="102372"
Name="ctx"
Access="Write"
Access_block="(538,4)"
Home_block="(538,4)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(278,2),(278,50)">
<Variable
Id="102373"
Name="ctx"
Access="Write"
Access_block="(538,4)"
Home_block="(538,4)"/>
</Data>
<Conditional
Code_Loc="(284,2),(285,21)">
</Conditional>
</Point_Block>
</CICB>
<CICB
Id="5"
Name="_PrintExtraToc">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13799 
</Call_invoke_IDs>
<Variable_access_IDs>
102374
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
102374
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(298,2),(302,27)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(298,2),(298,51)">
<Variable
Id="102374"
Name="ctx"
Access="Write"
Access_block="(538,5)"
Home_block="(538,5)"/>
</Data>
<Conditional
Code_Loc="(300,2),(302,27)">
</Conditional>
</Point_Block>
</CICB>
<CICB
Id="6"
Name="_StartData">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="9">
<Call_invoke_IDs>
13787 
</Call_invoke_IDs>
<Variable_access_IDs>
102375
102376
102377
102378
102379
102380
102381
102382
102383
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="4"
Num_Variable_accesses="9">
<Call_invoke_IDs>
13807 
13808 
13708 
13809 
</Call_invoke_IDs>
<Variable_access_IDs>
102375
102376
102377
102378
102379
102380
102381
102382
102383
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="7"
Braced="Yes"
Code_Loc="(318,2),(327,30)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(318,2),(318,49)">
<Variable
Id="102375"
Name="ctx"
Access="Write"
Access_block="(538,6)"
Home_block="(538,6)"/>
<Variable
Id="102376"
Name="AH"
Access="Read"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(319,2),(319,52)">
<Variable
Id="102377"
Name="tctx"
Access="Write"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(321,2),(321,38)">
<Variable
Id="102378"
Name="tctx"
Access="Write"
Access_block="(538,6)"
Home_block="(538,6)"/>
<Call
Id="13807"
Name="_getFilePos"
Collect="Absorbed"
Access_block="(538,6)"
Home_block="(538,24)">
<Data
Data_owner="CallParamaters"
Code_Loc="(321,2),(321,38)">
<Variable
Id="102379"
Name="AH"
Access="Read"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(322,2),(322,36)">
<Variable
Id="102380"
Name="tctx"
Access="Write"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(324,2),(324,26)">
<Call
Id="13808"
Name="_WriteByte"
Collect="Absorbed"
Access_block="(538,6)"
Home_block="(538,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(324,2),(324,26)">
<Variable
Id="102381"
Name="AH"
Access="Read"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(325,2),(325,26)">
<Call
Id="13708"
Name="WriteInt"
Collect="Absorbed"
Access_block="(538,6)"
Home_block="(537,34)">
<Data
Data_owner="CallParamaters"
Code_Loc="(325,2),(325,26)">
<Variable
Id="102382"
Name="AH"
Access="Read"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(327,2),(327,30)">
<Call
Id="13809"
Name="_StartDataCompressor"
Collect="Absorbed"
Access_block="(538,6)"
Home_block="(538,26)">
<Data
Data_owner="CallParamaters"
Code_Loc="(327,2),(327,30)">
<Variable
Id="102383"
Name="AH"
Access="Read"
Access_block="(538,6)"
Home_block="(538,6)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="7"
Name="_WriteData">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="8">
<Call_invoke_IDs>
13788 
</Call_invoke_IDs>
<Variable_access_IDs>
102384
102385
102386
102387
102388
102389
102390
102391
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="8">
<Call_invoke_IDs>
13810 
</Call_invoke_IDs>
<Variable_access_IDs>
102384
102385
102386
102387
102388
102389
102390
102391
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(342,2),(353,13)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(342,2),(342,49)">
<Variable
Id="102384"
Name="ctx"
Access="Write"
Access_block="(538,7)"
Home_block="(538,7)"/>
<Variable
Id="102385"
Name="AH"
Access="Read"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(343,2),(343,24)">
<Variable
Id="102386"
Name="ctx"
Access="Write"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(345,2),(345,29)">
<Variable
Id="102387"
Name="data"
Access="Write"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(346,2),(346,21)">
<Variable
Id="102388"
Name="dLen"
Access="Write"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
<Cyclic
Id="5168"
Code_Loc="(348,2),(352,2)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(351,3),(351,25)">
<Data
Data_owner="Expression"
Code_Loc="(351,3),(351,25)">
<Call
Id="13810"
Name="_DoDeflate"
Collect="Absorbed"
Access_block="(538,7)"
Home_block="(538,27)">
<Data
Data_owner="CallParamaters"
Code_Loc="(351,3),(351,25)">
<Variable
Id="102389"
Name="AH"
Access="Read"
Access_block="(538,7)"
Home_block="(538,7)"/>
<Variable
Id="102390"
Name="ctx"
Access="Read"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
</Call>
</Data>
</Point_Block>
</Cyclic>
<Data
Data_owner="Jump"
Code_Loc="(353,2),(353,13)">
<Variable
Id="102391"
Name="dLen"
Access="Read"
Access_block="(538,7)"
Home_block="(538,7)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="8"
Name="_EndData">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13789 
</Call_invoke_IDs>
<Variable_access_IDs>
102392
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13811 
</Call_invoke_IDs>
<Variable_access_IDs>
102392
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(369,2),(369,28)">
<Data
Data_owner="Expression"
Code_Loc="(369,2),(369,28)">
<Call
Id="13811"
Name="_EndDataCompressor"
Collect="Bridged"
Access_block="(538,8)"
Home_block="(538,28)">
<Data
Data_owner="CallParamaters"
Code_Loc="(369,2),(369,28)">
<Variable
Id="102392"
Name="AH"
Access="Read"
Access_block="(538,8)"
Home_block="(538,8)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="9"
Name="_StartBlobs">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="8">
<Call_invoke_IDs>
13800 
</Call_invoke_IDs>
<Variable_access_IDs>
102393
102394
102395
102396
102397
102398
102399
102400
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="3"
Num_Variable_accesses="8">
<Call_invoke_IDs>
13812 
13813 
13709 
</Call_invoke_IDs>
<Variable_access_IDs>
102393
102394
102395
102396
102397
102398
102399
102400
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(384,2),(391,26)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(384,2),(384,49)">
<Variable
Id="102393"
Name="ctx"
Access="Write"
Access_block="(538,9)"
Home_block="(538,9)"/>
<Variable
Id="102394"
Name="AH"
Access="Read"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(385,2),(385,52)">
<Variable
Id="102395"
Name="tctx"
Access="Write"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(387,2),(387,38)">
<Variable
Id="102396"
Name="tctx"
Access="Write"
Access_block="(538,9)"
Home_block="(538,9)"/>
<Call
Id="13812"
Name="_getFilePos"
Collect="Absorbed"
Access_block="(538,9)"
Home_block="(538,24)">
<Data
Data_owner="CallParamaters"
Code_Loc="(387,2),(387,38)">
<Variable
Id="102397"
Name="AH"
Access="Read"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(388,2),(388,36)">
<Variable
Id="102398"
Name="tctx"
Access="Write"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(390,2),(390,27)">
<Call
Id="13813"
Name="_WriteByte"
Collect="Absorbed"
Access_block="(538,9)"
Home_block="(538,18)">
<Data
Data_owner="CallParamaters"
Code_Loc="(390,2),(390,27)">
<Variable
Id="102399"
Name="AH"
Access="Read"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(391,2),(391,26)">
<Call
Id="13709"
Name="WriteInt"
Collect="Absorbed"
Access_block="(538,9)"
Home_block="(537,34)">
<Data
Data_owner="CallParamaters"
Code_Loc="(391,2),(391,26)">
<Variable
Id="102400"
Name="AH"
Access="Read"
Access_block="(538,9)"
Home_block="(538,9)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="10"
Name="_StartBlob">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="2">
<Call_invoke_IDs>
13801 
</Call_invoke_IDs>
<Variable_access_IDs>
102401
102402
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="2"
Num_Variable_accesses="2">
<Call_invoke_IDs>
13710 
13814 
</Call_invoke_IDs>
<Variable_access_IDs>
102401
102402
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(404,2),(408,30)">
<Conditional
Code_Loc="(404,2),(405,65)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(407,2),(407,19)">
<Call
Id="13710"
Name="WriteInt"
Collect="Absorbed"
Access_block="(538,10)"
Home_block="(537,34)">
<Data
Data_owner="CallParamaters"
Code_Loc="(407,2),(407,19)">
<Variable
Id="102401"
Name="AH"
Access="Read"
Access_block="(538,10)"
Home_block="(538,10)"/>
</Data>
</Call>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(408,2),(408,30)">
<Call
Id="13814"
Name="_StartDataCompressor"
Collect="Absorbed"
Access_block="(538,10)"
Home_block="(538,26)">
<Data
Data_owner="CallParamaters"
Code_Loc="(408,2),(408,30)">
<Variable
Id="102402"
Name="AH"
Access="Read"
Access_block="(538,10)"
Home_block="(538,10)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="11"
Name="_EndBlob">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13802 
</Call_invoke_IDs>
<Variable_access_IDs>
102403
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13815 
</Call_invoke_IDs>
<Variable_access_IDs>
102403
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(419,2),(419,28)">
<Data
Data_owner="Expression"
Code_Loc="(419,2),(419,28)">
<Call
Id="13815"
Name="_EndDataCompressor"
Collect="Bridged"
Access_block="(538,11)"
Home_block="(538,28)">
<Data
Data_owner="CallParamaters"
Code_Loc="(419,2),(419,28)">
<Variable
Id="102403"
Name="AH"
Access="Read"
Access_block="(538,11)"
Home_block="(538,11)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="12"
Name="_EndBlobs">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13803 
</Call_invoke_IDs>
<Variable_access_IDs>
102404
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="1">
<Call_invoke_IDs>
13711 
</Call_invoke_IDs>
<Variable_access_IDs>
102404
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(431,2),(431,17)">
<Data
Data_owner="Expression"
Code_Loc="(431,2),(431,17)">
<Call
Id="13711"
Name="WriteInt"
Collect="Absorbed"
Access_block="(538,12)"
Home_block="(537,34)">
<Data
Data_owner="CallParamaters"
Code_Loc="(431,2),(431,17)">
<Variable
Id="102404"
Name="AH"
Access="Read"
Access_block="(538,12)"
Home_block="(538,12)"/>
</Data>
</Call>
</Data>
</Point_Block>
</CICB>
<CICB
Id="13"
Name="_PrintTocData">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="11">
<Call_invoke_IDs>
13796 
</Call_invoke_IDs>
<Variable_access_IDs>
102405
102406
102407
102408
102409
102410
102411
102412
102413
102414
102415
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="7"
Num_Variable_accesses="11">
<Call_invoke_IDs>
13816 
13817 
13818 
13819 
13820 
13821 
13822 
</Call_invoke_IDs>
<Variable_access_IDs>
102405
102406
102407
102408
102409
102410
102411
102412
102413
102414
102415
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="7"
Braced="Yes"
Code_Loc="(440,2),(511,2)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(440,2),(440,49)">
<Variable
Id="102405"
Name="ctx"
Access="Write"
Access_block="(538,13)"
Home_block="(538,13)"/>
<Variable
Id="102406"
Name="AH"
Access="Read"
Access_block="(538,13)"
Home_block="(538,13)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(442,2),(442,52)">
<Variable
Id="102407"
Name="tctx"
Access="Write"
Access_block="(538,13)"
Home_block="(538,13)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(444,2),(444,17)">
<Variable
Id="102408"
Name="found"
Access="Write"
Access_block="(538,13)"
Home_block="(538,13)"/>
</Data>
<Conditional
Code_Loc="(446,2),(447,9)">
</Conditional>
<Selective
If_Blocks="Yes"
Code_Loc="(449,2),(490,2)">
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(453,3),(481,3)">
<Data
Data_owner="Expression"
Code_Loc="(453,3),(453,12)">
<Variable
Id="102409"
Name="found"
Access="Write"
Access_block="(538,13)"
Home_block="(538,13)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(455,3),(455,38)">
<Call
Id="13816"
Name="_readBlockHeader"
Collect="Absorbed"
Access_block="(538,13)"
Home_block="(538,25)">
<Data
Data_owner="CallParamaters"
Code_Loc="(455,3),(455,38)">
<Variable
Id="102410"
Name="AH"
Access="Read"
Access_block="(538,13)"
Home_block="(538,13)"/>
<Variable
Id="102411"
Name="blkType"
Access="Read"
Access_block="(538,13)"