<?xml version = "1.0"?>
<!DOCTYPE Component [
<!ELEMENT Component (CICB*)>
<!ATTLIST Component
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Num_CICBs CDATA #REQUIRED>
<!ELEMENT CICB (Provide|Require|Block_Point|EMPTY)>
<!ATTLIST CICB
Id CDATA #REQUIRED
Name CDATA #REQUIRED>
<!ELEMENT Provide (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Require (Call_invoke_IDs|Variable_access_IDs|EMPTY)>
<!ATTLIST Provide
Num_call_invokes CDATA #REQUIRED
Num_Variable_accesses CDATA #REQUIRED>
<!ELEMENT Call_invoke_IDs EMPTY>
<!ELEMENT Variable_access_IDs EMPTY>
<!ELEMENT Point_Block (Selective|Conditional|Cyclic|Data)*>
<!ATTLIST Provide
Num_points CDATA #REQUIRED
Braced CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Selective (Point_Block*|EMPTY)>
<!ATTLIST Selective
If_Blocks CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Conditional (Point_Block|EMPTY)>
<!ATTLIST Conditional
Code_Loc CDATA #REQUIRED>
<!ELEMENT Cyclic (Point_Block|EMPTY)>
<!ATTLIST Cyclic
Id CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Data (Call|Variable|EMPTY)*>
<!ATTLIST Data
Data_owner CDATA #REQUIRED
Code_Loc CDATA #REQUIRED>
<!ELEMENT Call (Data|EMPTY)>
<!ATTLIST Call
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Collect CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
Id CDATA #REQUIRED
Name CDATA #REQUIRED
Access CDATA #REQUIRED
Access_block CDATA #REQUIRED
Home_block CDATA #REQUIRED>
]>
<Component
Id="206"
Name="backend.optimizer.path.costsize.c"
Num_CICBs="41">
<CICB
Id="0"
Name="Master">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="0">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="16">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38179
38180
38181
38182
38183
38184
38185
38186
38187
38188
38189
38190
38191
38192
38193
38194
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="16"
Braced="Yes"
Code_Loc="(93,1),(3036,1)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(93,1),(93,46)">
<Variable
Id="38179"
Name="seq_page_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(94,1),(94,52)">
<Variable
Id="38180"
Name="random_page_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(95,1),(95,48)">
<Variable
Id="38181"
Name="cpu_tuple_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(96,1),(96,60)">
<Variable
Id="38182"
Name="cpu_index_tuple_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(97,1),(97,54)">
<Variable
Id="38183"
Name="cpu_operator_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(99,1),(99,58)">
<Variable
Id="38184"
Name="effective_cache_size"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(101,1),(101,28)">
<Variable
Id="38185"
Name="disable_cost"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(103,1),(103,28)">
<Variable
Id="38186"
Name="enable_seqscan"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(104,1),(104,30)">
<Variable
Id="38187"
Name="enable_indexscan"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(105,1),(105,31)">
<Variable
Id="38188"
Name="enable_bitmapscan"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(106,1),(106,28)">
<Variable
Id="38189"
Name="enable_tidscan"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(107,1),(107,25)">
<Variable
Id="38190"
Name="enable_sort"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(108,1),(108,28)">
<Variable
Id="38191"
Name="enable_hashagg"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(109,1),(109,29)">
<Variable
Id="38192"
Name="enable_nestloop"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(110,1),(110,30)">
<Variable
Id="38193"
Name="enable_mergejoin"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(111,1),(111,29)">
<Variable
Id="38194"
Name="enable_hashjoin"
Access="Write"
Access_block="(206,0)"
Home_block="(945,0)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="1"
Name="clamp_row_est">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38195
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="1">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38195
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(147,2),(152,14)">
<Selective
If_Blocks="Yes"
Code_Loc="(147,2),(150,22)">
</Selective>
<Data
Data_owner="Jump"
Code_Loc="(152,2),(152,14)">
<Variable
Id="38195"
Name="nrows"
Access="Read"
Access_block="(206,1)"
Home_block="(206,1)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="2"
Name="cost_seqscan">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="19">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38196
38197
38198
38199
38200
38202
38203
38204
38205
38207
38208
38209
38210
38211
38212
38213
38214
38215
38216
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="21">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38196
38197
38198
38199
38200
38201
38202
38203
38204
38205
38206
38207
38208
38209
38210
38211
38212
38213
38214
38215
38216
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="11"
Braced="Yes"
Code_Loc="(164,2),(186,44)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(164,2),(164,24)">
<Variable
Id="38196"
Name="startup_cost"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(165,2),(165,20)">
<Variable
Id="38197"
Name="run_cost"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(169,2),(169,28)">
<Variable
Id="38198"
Name="baserel"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(170,2),(170,42)">
<Variable
Id="38199"
Name="baserel"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Conditional
Code_Loc="(172,2),(173,31)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(178,2),(178,44)">
<Variable
Id="38200"
Name="run_cost"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38201"
Name="seq_page_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(945,0)"/>
<Variable
Id="38202"
Name="baserel"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(181,2),(181,51)">
<Variable
Id="38203"
Name="startup_cost"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38204"
Name="baserel"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(182,2),(182,70)">
<Variable
Id="38205"
Name="cpu_per_tuple"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38206"
Name="cpu_tuple_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(945,0)"/>
<Variable
Id="38207"
Name="baserel"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(183,2),(183,45)">
<Variable
Id="38208"
Name="run_cost"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38209"
Name="cpu_per_tuple"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38210"
Name="baserel"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(185,2),(185,35)">
<Variable
Id="38211"
Name="path"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38212"
Name="startup_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38213"
Name="startup_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(186,2),(186,44)">
<Variable
Id="38214"
Name="path"
Access="Write"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38215"
Name="startup_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
<Variable
Id="38216"
Name="run_cost"
Access="Read"
Access_block="(206,2)"
Home_block="(206,2)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="3"
Name="cost_index">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="59">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38217
38218
38219
38220
38221
38222
38223
38224
38225
38226
38227
38228
38229
38230
38231
38232
38233
38234
38235
38236
38237
38238
38239
38241
38242
38243
38244
38245
38246
38248
38249
38250
38251
38253
38254
38255
38257
38258
38259
38260
38261
38262
38263
38264
38265
38266
38268
38269
38270
38271
38272
38273
38274
38275
38276
38277
38278
38279
38280
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="64">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38217
38218
38219
38220
38221
38222
38223
38224
38225
38226
38227
38228
38229
38230
38231
38232
38233
38234
38235
38236
38237
38238
38239
38240
38241
38242
38243
38244
38245
38246
38247
38248
38249
38250
38251
38252
38253
38254
38255
38256
38257
38258
38259
38260
38261
38262
38263
38264
38265
38266
38267
38268
38269
38270
38271
38272
38273
38274
38275
38276
38277
38278
38279
38280
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="20"
Braced="Yes"
Code_Loc="(218,2),(384,49)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(218,2),(218,34)">
<Variable
Id="38217"
Name="RelOptInfo"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38218"
Name="index"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(219,2),(219,24)">
<Variable
Id="38219"
Name="startup_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(220,2),(220,20)">
<Variable
Id="38220"
Name="run_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(233,2),(234,31)">
<Variable
Id="38221"
Name="RelOptInfo"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38222"
Name="index"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38223"
Name="IndexOptInfo"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Conditional
Code_Loc="(238,2),(239,31)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(247,2),(255,42)">
<Variable
Id="38224"
Name="index"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(262,2),(262,39)">
<Variable
Id="38225"
Name="path"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38226"
Name="indexTotalCost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(263,2),(263,43)">
<Variable
Id="38227"
Name="path"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38228"
Name="indexSelectivity"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(266,2),(266,34)">
<Variable
Id="38229"
Name="startup_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38230"
Name="indexStartupCost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(267,2),(267,47)">
<Variable
Id="38231"
Name="run_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38232"
Name="indexTotalCost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38233"
Name="indexStartupCost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(270,2),(270,68)">
<Variable
Id="38234"
Name="tuples_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(292,2),(349,2)">
<Point_Block
Num_points="6"
Braced="Yes"
Code_Loc="(302,3),(328,63)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(302,3),(302,38)">
<Variable
Id="38235"
Name="num_scans"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38236"
Name="outer_rel"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(304,3),(307,17)">
<Variable
Id="38237"
Name="pages_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(309,3),(309,63)">
<Variable
Id="38238"
Name="max_IO_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38239"
Name="pages_fetched"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38240"
Name="random_page_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(945,0)"/>
<Variable
Id="38241"
Name="num_scans"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(321,3),(321,67)">
<Variable
Id="38242"
Name="pages_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38243"
Name="indexSelectivity"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(323,3),(326,17)">
<Variable
Id="38244"
Name="pages_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(328,3),(328,63)">
<Variable
Id="38245"
Name="min_IO_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38246"
Name="pages_fetched"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38247"
Name="random_page_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(945,0)"/>
<Variable
Id="38248"
Name="num_scans"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="5"
Braced="Yes"
Code_Loc="(336,3),(348,54)">
<Data
Data_owner="Expression"
Code_Loc="(336,3),(339,17)">
<Variable
Id="38249"
Name="pages_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(342,3),(342,49)">
<Variable
Id="38250"
Name="max_IO_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38251"
Name="pages_fetched"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38252"
Name="random_page_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(945,0)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(345,3),(345,67)">
<Variable
Id="38253"
Name="pages_fetched"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38254"
Name="indexSelectivity"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(346,3),(346,33)">
<Variable
Id="38255"
Name="min_IO_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38256"
Name="random_page_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(945,0)"/>
</Data>
<Conditional
Code_Loc="(347,3),(348,54)">
</Conditional>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(355,2),(355,48)">
<Variable
Id="38257"
Name="csquared"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38258"
Name="indexCorrelation"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38259"
Name="indexCorrelation"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(357,2),(357,66)">
<Variable
Id="38260"
Name="run_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38261"
Name="max_IO_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38262"
Name="csquared"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38263"
Name="min_IO_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38264"
Name="max_IO_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(369,2),(369,51)">
<Variable
Id="38265"
Name="startup_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(370,2),(370,70)">
<Variable
Id="38266"
Name="cpu_per_tuple"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38267"
Name="cpu_tuple_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(945,0)"/>
</Data>
<Conditional
Code_Loc="(372,2),(379,2)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(374,3),(378,45)">
<Data
Data_owner="Expression"
Code_Loc="(378,3),(378,45)">
<Variable
Id="38268"
Name="cpu_per_tuple"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38269"
Name="index_qual_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
</Point_Block>
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(381,2),(381,44)">
<Variable
Id="38270"
Name="run_cost"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38271"
Name="cpu_per_tuple"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38272"
Name="tuples_fetched"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(383,2),(383,40)">
<Variable
Id="38273"
Name="path"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38274"
Name="path"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38275"
Name="startup_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38276"
Name="startup_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(384,2),(384,49)">
<Variable
Id="38277"
Name="path"
Access="Write"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38278"
Name="path"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38279"
Name="startup_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
<Variable
Id="38280"
Name="run_cost"
Access="Read"
Access_block="(206,3)"
Home_block="(206,3)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="4"
Name="index_pages_fetched">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="35">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38281
38282
38283
38284
38285
38286
38287
38288
38290
38291
38292
38293
38294
38295
38296
38297
38298
38299
38300
38301
38302
38303
38304
38305
38306
38307
38308
38309
38310
38311
38312
38313
38314
38315
38316
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="36">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38281
38282
38283
38284
38285
38286
38287
38288
38289
38290
38291
38292
38293
38294
38295
38296
38297
38298
38299
38300
38301
38302
38303
38304
38305
38306
38307
38308
38309
38310
38311
38312
38313
38314
38315
38316
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="8"
Braced="Yes"
Code_Loc="(429,2),(478,22)">
<Data
Data_owner="Expression"
Code_Loc="(435,2),(435,40)">
<Variable
Id="38281"
Name="T"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(438,2),(438,53)">
<Variable
Id="38282"
Name="total_pages"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38283"
Name="index_pages"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(439,2),(439,37)">
<Variable
Id="38284"
Name="total_pages"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38285"
Name="total_pages"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(440,2),(440,26)">
<Variable
Id="38286"
Name="T"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38287"
Name="total_pages"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(443,2),(443,52)">
<Variable
Id="38288"
Name="b"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38289"
Name="effective_cache_size"
Access="Read"
Access_block="(206,4)"
Home_block="(945,0)"/>
<Variable
Id="38290"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38291"
Name="total_pages"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(446,2),(449,14)">
</Selective>
<Selective
If_Blocks="Yes"
Code_Loc="(452,2),(477,2)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(454,3),(459,39)">
<Data
Data_owner="Expression"
Code_Loc="(454,3),(455,59)">
<Variable
Id="38292"
Name="pages_fetched"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38293"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38294"
Name="tuples_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38295"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38296"
Name="tuples_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(456,3),(459,39)">
</Selective>
</Point_Block>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(463,3),(476,38)">
<Data
Data_owner="Expression"
Code_Loc="(465,3),(465,38)">
<Variable
Id="38297"
Name="lim"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38298"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38299"
Name="b"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38300"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38301"
Name="b"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(466,3),(475,3)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(468,4),(469,60)">
<Data
Data_owner="Expression"
Code_Loc="(468,4),(469,60)">
<Variable
Id="38302"
Name="pages_fetched"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38303"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38304"
Name="tuples_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38305"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38306"
Name="tuples_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(473,4),(474,45)">
<Data
Data_owner="Expression"
Code_Loc="(473,4),(474,45)">
<Variable
Id="38307"
Name="pages_fetched"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38308"
Name="b"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38309"
Name="tuples_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38310"
Name="lim"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38311"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38312"
Name="b"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38313"
Name="T"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
</Point_Block>
</Selective>
<Data
Data_owner="Expression"
Code_Loc="(476,3),(476,38)">
<Variable
Id="38314"
Name="pages_fetched"
Access="Write"
Access_block="(206,4)"
Home_block="(206,4)"/>
<Variable
Id="38315"
Name="pages_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
</Point_Block>
</Selective>
<Data
Data_owner="Jump"
Code_Loc="(478,2),(478,22)">
<Variable
Id="38316"
Name="pages_fetched"
Access="Read"
Access_block="(206,4)"
Home_block="(206,4)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="5"
Name="get_indexpath_pages">
<Provide
Num_call_invokes="1"
Num_Variable_accesses="5">
<Call_invoke_IDs>
7643 
</Call_invoke_IDs>
<Variable_access_IDs>
38317
38318
38319
38320
38321
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="1"
Num_Variable_accesses="5">
<Call_invoke_IDs>
7643 
</Call_invoke_IDs>
<Variable_access_IDs>
38317
38318
38319
38320
38321
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(493,2),(523,15)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(493,2),(493,20)">
<Variable
Id="38317"
Name="result"
Access="Write"
Access_block="(206,5)"
Home_block="(206,5)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(496,2),(521,65)">
<Point_Block
Num_points="2"
Braced="Yes"
Code_Loc="(498,3),(503,3)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(498,3),(498,54)">
<Variable
Id="38318"
Name="bitmapqual"
Access="Write"
Access_block="(206,5)"
Home_block="(206,5)"/>
</Data>
<Cyclic
Id="2426"
Code_Loc="(500,3),(503,3)">
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(502,4),(502,53)">
<Data
Data_owner="Expression"
Code_Loc="(502,4),(502,53)">
<Variable
Id="38319"
Name="result"
Access="Write"
Access_block="(206,5)"
Home_block="(206,5)"/>
<Call
Id="7643"
Name="get_indexpath_pages"
Collect="Bridged"
Access_block="(206,5)"
Home_block="(206,5)">
<Data
Data_owner="CallParamaters"
Code_Loc="(502,4),(502,53)">
<Variable
Id="38320"
Name="l"
Access="Read"
Access_block="(206,5)"
Home_block="(206,5)"/>
</Data>
</Call>
</Data>
</Point_Block>
</Cyclic>
</Point_Block>
</Selective>
<Data
Data_owner="Jump"
Code_Loc="(523,2),(523,15)">
<Variable
Id="38321"
Name="result"
Access="Read"
Access_block="(206,5)"
Home_block="(206,5)"/>
</Data>
</Point_Block>
</CICB>
<CICB
Id="6"
Name="cost_bitmap_heap_scan">
<Provide
Num_call_invokes="0"
Num_Variable_accesses="31">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38322
38323
38324
38325
38326
38327
38328
38329
38330
38331
38332
38333
38334
38335
38336
38337
38338
38339
38340
38341
38342
38343
38345
38346
38347
38348
38349
38350
38351
38352
38353
</Variable_access_IDs>
</Provide>
<Require
Num_call_invokes="0"
Num_Variable_accesses="32">
<Call_invoke_IDs>
</Call_invoke_IDs>
<Variable_access_IDs>
38322
38323
38324
38325
38326
38327
38328
38329
38330
38331
38332
38333
38334
38335
38336
38337
38338
38339
38340
38341
38342
38343
38344
38345
38346
38347
38348
38349
38350
38351
38352
38353
</Variable_access_IDs>
</Require>
<Point_Block
Num_points="16"
Braced="Yes"
Code_Loc="(545,2),(637,44)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(545,2),(545,24)">
<Variable
Id="38322"
Name="startup_cost"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="VariableDeclaration"
Code_Loc="(546,2),(546,20)">
<Variable
Id="38323"
Name="run_cost"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(556,2),(556,34)">
<Variable
Id="38324"
Name="RelOptInfo"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Conditional
Code_Loc="(560,2),(561,31)">
</Conditional>
<Data
Data_owner="Expression"
Code_Loc="(569,2),(569,32)">
<Variable
Id="38325"
Name="startup_cost"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38326"
Name="indexTotalCost"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(574,2),(574,68)">
<Variable
Id="38327"
Name="tuples_fetched"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(576,2),(576,58)">
<Variable
Id="38328"
Name="T"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Selective
If_Blocks="Yes"
Code_Loc="(578,2),(602,2)">
<Point_Block
Num_points="3"
Braced="Yes"
Code_Loc="(586,3),(592,29)">
<Data
Data_owner="VariableDeclaration"
Code_Loc="(586,3),(586,38)">
<Variable
Id="38329"
Name="num_scans"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38330"
Name="outer_rel"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(588,3),(591,17)">
<Variable
Id="38331"
Name="pages_fetched"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
<Data
Data_owner="Expression"
Code_Loc="(592,3),(592,29)">
<Variable
Id="38332"
Name="pages_fetched"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38333"
Name="num_scans"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
</Data>
</Point_Block>
<Point_Block
Num_points="1"
Braced="Yes"
Code_Loc="(601,3),(601,74)">
<Data
Data_owner="Expression"
Code_Loc="(601,3),(601,74)">
<Variable
Id="38334"
Name="pages_fetched"
Access="Write"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38335"
Name="T"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38336"
Name="tuples_fetched"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38337"
Name="T"
Access="Read"
Access_block="(206,6)"
Home_block="(206,6)"/>
<Variable
Id="38338"
Name="tuples_fetched"